services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ..:/app
    environment:
      - FLASK_APP=wsgi.py
      - FLASK_ENV=production
    restart: unless-stopped

  redis:
    image: redis:latest
    ports:
      - 6380:6379
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
    name: redis_data